spring.application.name=BMS

# Database
spring.datasource.url=jdbc:postgresql://ep-odd-poetry-aq465rvd-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PcmrZ1LCkB5S
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# JWT
jwt.secret=${JWT_SECRET:ThisIsAVeryStrongSecretKeyForBMSProject2026@123456}
jwt.expiration=86400000

# Render provides PORT automatically
server.port=${PORT:8080}